### ISSUE TITLE
The program is Mohex or Mohex2.0?

### ISSUE THREAD

**Issue by vigor95** [cgao3/benzene-vanilla-cmake#3]
Is the "Mohex" in this repo Mohex2.0?

**Comment by cgao3** [comment]
mohex2.0

**Comment by vigor95** [comment]
Thanks for your reply. I also want to know if there is any program available on the internet that is stronger than Mohex2.0(on 13x13).

**Comment by cgao3** [comment]
It is easy to stronger than MoHex2.0 if a properly trained neural net is added.
You can check gzero  https://github.com/richemslie/galvanise_zero

There are also other programs, e.g., our not-yet-released neurobenzene, DeepEzo by Kei Takada from Japan etc. I am not sure if those programs are open source or not.

**Comment by vigor95** [comment]
Thanks a lot for your help.
